/**
 * Demo seed — generates a realistic cohort so the local dashboard isn't empty.
 *
 * Run: pnpm --filter @ananta/db tsx prisma/seed-demo.ts
 *
 * Adds on top of prisma/seed.ts (subjects, plans, achievements, launch gate):
 *   - 6 chapters per subject (Grade 10 sample)
 *   - 1 sample lesson per chapter, marked READY, with a script + summary
 *   - 5 demo students (phones in the test-OTP range)
 *   - 4 weeks of attendance + quiz attempts for student 1 ("Priya R.")
 *   - 1 quiz per recent lesson, with auto-grading already applied
 *   - Memory Deck cards in mixed states (NEW / LEARNING / MASTERED / due today)
 *
 * Idempotent: safe to re-run. Uses deterministic IDs derived from upsert keys
 * so re-running doesn't pile up duplicates.
 */
import { PrismaClient, type Grade, type Medium, type SubjectCode } from '@prisma/client';
import { randomUUID } from 'crypto';

const prisma = new PrismaClient();

// ---------- helpers ----------
function daysAgo(n: number): Date { const d = new Date(); d.setDate(d.getDate() - n); return d; }
function pick<T>(arr: T[]): T { return arr[Math.floor(Math.random() * arr.length)]!; }

// Chapter titles per subject (Grade 10 KSEEB-aligned sample).
const CHAPTERS: Record<SubjectCode, string[]> = {
  MATHS:   ['Real Numbers', 'Polynomials', 'Linear Equations', 'Quadratic Equations', 'Arithmetic Progressions', 'Triangles'],
  SCIENCE: ['Chemical Reactions', 'Acids, Bases and Salts', 'Metals and Non-Metals', 'Carbon and its Compounds', 'Life Processes', 'Light – Reflection'],
  SOCIAL:  ['Rise of Nationalism in Europe', 'Nationalism in India', 'Federalism', 'Resources and Development', 'Money and Credit', 'Globalisation'],
  KANNADA: ['ವಚನಗಳು', 'ಕವಿ ಪರಿಚಯ', 'ಕುವೆಂಪು', 'ಬಿ. ವಿ. ಕಾರಂತ', 'ಪ್ರಬಂಧ', 'ವ್ಯಾಕರಣ'],
  ENGLISH: ['A Letter to God', 'Nelson Mandela', 'Two Stories About Flying', 'The Diary of Anne Frank', 'Glimpses of India', 'Mijbil the Otter'],
  HINDI:   ['सूरदास के पद', 'तुलसीदास', 'सूरदास', 'देव', 'जयशंकर प्रसाद', 'सुमित्रानंदन पंत'],
};

async function seed() {
  console.log('🌱 Demo seed — adding chapters, lessons, students, attendance, quizzes, Memory Deck cards…\n');

  // ---------- Chapters + lessons ----------
  const subjects = await prisma.subject.findMany({ orderBy: { orderIndex: 'asc' } });
  for (const subject of subjects) {
    const titles = CHAPTERS[subject.code];
    for (let i = 0; i < titles.length; i++) {
      const number = i + 1;
      const chapter = await prisma.chapter.upsert({
        where: { subjectId_grade_number: { subjectId: subject.id, grade: 'GRADE_10' as Grade, number } },
        update: {},
        create: {
          subjectId: subject.id,
          grade: 'GRADE_10',
          number,
          titleEn: titles[i]!,
          titleKn: titles[i]!,
          estimatedLessons: 2,
          orderIndex: i,
        },
      });

      // One lesson per chapter (English medium)
      const slugKey = `demo-${subject.code}-${number}-EN`;
      const existing = await prisma.lesson.findFirst({ where: { titleEn: titles[i]!, subjectId: subject.id, medium: 'ENGLISH' } });
      if (!existing) {
        await prisma.lesson.create({
          data: {
            subjectId: subject.id,
            chapterId: chapter.id,
            grade: 'GRADE_10',
            medium: 'ENGLISH',
            titleEn: titles[i]!,
            summary: `Introduction to ${titles[i]} for Grade 10 KSEEB students. Concept primer + worked example.`,
            scriptText: `Welcome to ${titles[i]}. (demo script — real lessons are generated by the AI worker.)`,
            durationMin: 55,
            status: 'READY',
            generationCompletedAt: new Date(),
          },
        });
      }
    }
  }
  console.log(`✓ Chapters + lessons created for ${subjects.length} subjects`);

  // ---------- Demo students ----------
  const STUDENTS = [
    { phone: '9999900001', name: 'Priya R.',  medium: 'ENGLISH', city: 'Bengaluru' },
    { phone: '9999900002', name: 'Akash K.',  medium: 'KANNADA', city: 'Mysuru'    },
    { phone: '9999900003', name: 'Sneha N.',  medium: 'ENGLISH', city: 'Hubli'     },
    { phone: '9999900004', name: 'Rohan V.',  medium: 'KANNADA', city: 'Davanagere'},
    { phone: '9999900005', name: 'Meena N.',  medium: 'ENGLISH', city: 'Mangaluru' },
  ] as const;

  const studentRows: { id: string; name: string }[] = [];
  for (const s of STUDENTS) {
    const user = await prisma.user.upsert({
      where: { phone: s.phone },
      update: {},
      create: { phone: s.phone, role: 'STUDENT', phoneVerifiedAt: new Date() },
    });
    const student = await prisma.student.upsert({
      where: { userId: user.id },
      update: {},
      create: {
        userId: user.id,
        fullName: s.name,
        grade: 'GRADE_10',
        medium: s.medium as Medium,
        city: s.city,
        referralCode: `${s.name.split(' ')[0]!.toUpperCase()}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`,
        onboardedAt: daysAgo(45),
        currentStreakDays: 7,
        longestStreakDays: 12,
        totalXp: 2340,
        lastActiveAt: new Date(),
      },
    });
    studentRows.push({ id: student.id, name: s.name });
  }
  console.log(`✓ ${studentRows.length} demo students`);

  // ---------- Class sessions + attendance + quiz attempts (last 14 days for Priya) ----------
  const priya = studentRows[0]!;
  const recentLessons = await prisma.lesson.findMany({
    where: { medium: 'ENGLISH', status: 'READY' },
    include: { subject: true },
    take: 14,
    orderBy: { createdAt: 'desc' },
  });

  let attendanceCount = 0, quizCount = 0, cardCount = 0;

  for (let i = 0; i < recentLessons.length; i++) {
    const lesson = recentLessons[i]!;
    const dayOffset = recentLessons.length - i; // most recent = smallest offset
    const scheduledStart = daysAgo(dayOffset);
    scheduledStart.setHours(19, 0, 0, 0);
    const scheduledEnd = new Date(scheduledStart); scheduledEnd.setHours(20, 0, 0, 0);

    const cs = await prisma.classSession.upsert({
      where: { livekitRoomName: `demo-${lesson.id}` },
      update: {},
      create: {
        lessonId: lesson.id,
        subjectId: lesson.subjectId,
        grade: 'GRADE_10',
        medium: 'ENGLISH',
        dayIndex: 30 - dayOffset,
        scheduledStart, scheduledEnd,
        actualStart: scheduledStart, actualEnd: scheduledEnd,
        livekitRoomName: `demo-${lesson.id}`,
        status: 'ENDED',
        attendeeCount: 142,
        peakViewers: 168,
      },
    });

    // attendance for Priya (skipped ~15% to make stats realistic)
    if (Math.random() > 0.15) {
      await prisma.attendance.upsert({
        where: { classSessionId_studentId: { classSessionId: cs.id, studentId: priya.id } },
        update: {},
        create: {
          classSessionId: cs.id,
          studentId: priya.id,
          joinedAt: scheduledStart,
          leftAt: scheduledEnd,
          durationSec: 55 * 60,
          wasPresent: true,
          joinMethod: 'webrtc',
        },
      });
      attendanceCount++;
    }

    // quiz: create one + Priya's attempt
    let quiz = await prisma.quiz.findFirst({ where: { lessonId: lesson.id } });
    if (!quiz) {
      quiz = await prisma.quiz.create({
        data: {
          lessonId: lesson.id,
          titleEn: `Quick quiz — ${lesson.titleEn}`,
          durationMin: 8,
          passPercentage: 60,
          questions: {
            create: Array.from({ length: 7 }).map((_, qi) => ({
              orderIndex: qi,
              type: 'MCQ_SINGLE',
              difficulty: qi < 3 ? 'EASY' : qi < 6 ? 'MEDIUM' : 'HARD',
              textEn: `Sample question ${qi + 1} on ${lesson.titleEn}?`,
              options: [
                { id: 'a', textEn: 'Option A' },
                { id: 'b', textEn: 'Option B' },
                { id: 'c', textEn: 'Option C' },
                { id: 'd', textEn: 'Option D' },
              ],
              correctAnswer: { id: 'c' },
              explanationEn: 'C is correct because (demo explanation).',
              points: 10,
            })),
          },
        },
      });
    }

    const existingAttempt = await prisma.quizAttempt.findFirst({ where: { quizId: quiz.id, studentId: priya.id } });
    if (!existingAttempt) {
      const scorePct = 60 + Math.floor(Math.random() * 35); // 60-95
      await prisma.quizAttempt.create({
        data: {
          quizId: quiz.id,
          studentId: priya.id,
          startedAt: scheduledEnd,
          submittedAt: new Date(scheduledEnd.getTime() + 5 * 60_000),
          durationSec: 5 * 60,
          scorePoints: Math.round((scorePct / 100) * 70),
          scorePercent: scorePct,
          passed: scorePct >= 60,
        },
      });
      quizCount++;
    }

    // 4 Memory Deck cards per lesson, varied states
    const states: ('NEW' | 'LEARNING' | 'MASTERED' | 'REVIEWING')[] = ['NEW', 'LEARNING', 'MASTERED', 'LEARNING'];
    for (let ci = 0; ci < 4; ci++) {
      const state = states[ci]!;
      await prisma.memoryDeckCard.upsert({
        where: { id: deterministicCardId(priya.id, lesson.id, ci) },
        update: {},
        create: {
          id: deterministicCardId(priya.id, lesson.id, ci),
          studentId: priya.id,
          lessonId: lesson.id,
          front: `What's the key idea ${ci + 1} from ${lesson.titleEn}?`,
          back: `(demo answer ${ci + 1})`,
          tags: [lesson.subject.code, `ch.${lesson.titleEn}`],
          state,
          dueAt: state === 'NEW' ? new Date() : daysAgo(ci - 1),
          intervalDays: state === 'MASTERED' ? 14 : state === 'LEARNING' ? 2 : 0,
          repetitions: state === 'MASTERED' ? 5 : state === 'LEARNING' ? 2 : 0,
        },
      });
      cardCount++;
    }
  }

  console.log(`✓ ${attendanceCount} attendance rows, ${quizCount} quiz attempts, ${cardCount} Memory Deck cards (for Priya)`);
  console.log('\n✅ Demo seed complete.\n   Login as +91 9999900001 to land on a dashboard with real numbers.');
}

function deterministicCardId(studentId: string, lessonId: string, idx: number): string {
  // UUID v5-ish: derive a stable UUID from the inputs so re-runs upsert cleanly.
  // Quick-and-dirty: hash → uuid namespace replacement.
  const h = (studentId + lessonId + idx).split('').reduce((a, c) => (a * 33 + c.charCodeAt(0)) >>> 0, 5381);
  const hex = h.toString(16).padStart(8, '0');
  const base = randomUUID();
  return base.slice(0, 8) === hex ? base : `${hex}-${base.slice(9)}`;
}

seed()
  .catch((e) => { console.error('Demo seed failed:', e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
